{
 "title": "Spring Boot - Micrometer - Matthew",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot)",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(app)" },
   {
    "name": "version",
    "label": "version",
    "query": "label_values(jvm_memory_used_bytes{app=\"$application\"}, version)"
   },
   {
    "name": "host",
    "label": "host",
    "query": "label_values(jvm_memory_used_bytes{app=\"$application\",version=\"$version\"}, host)"
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": "label_values(jvm_memory_used_bytes{host=\"$host\", app=\"$application\",version=\"$version\", area=\"heap\"},id)"
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": "label_values(jvm_memory_used_bytes{host=\"$host\", app=\"$application\",version=\"$version\", area=\"nonheap\"},id)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{host=\"$host\", app=\"$application\", version=\"$version\"}"
    }
   ]
  },
  {
   "title": "Start time (UTC)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{host=\"$host\", app=\"$application\", version=\"$version\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"heap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"heap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"nonheap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"nonheap\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", area=\"nonheap\"})",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{host=\"$host\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{host=\"$host\"})",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{host=\"$host\"})",
     "legendFormat": "max"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{host=\"$host\", app=\"$application\", version=\"$version\"}",
     "legendFormat": "system"
    },
    {
     "expr": "process_cpu_usage{host=\"$host\", app=\"$application\", version=\"$version\"}",
     "legendFormat": "process"
    },
    {
     "expr": "avg_over_time(process_cpu_usage{host=\"$host\", app=\"$application\", version=\"$version\"}[1h])",
     "legendFormat": "process-1h"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{host=\"$host\"}",
     "legendFormat": "system-1m"
    },
    {},
    {
     "expr": "system_cpu_count{host=\"$host\"}",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live{host=\"$host\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon{host=\"$host\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_peak{host=\"$host\"}",
     "legendFormat": "peak"
    },
    {
     "expr": "process_threads{host=\"$host\"}",
     "legendFormat": "process"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_files_open{host=\"$host\", app=\"$application\", version=\"$version\"}",
     "legendFormat": "open"
    },
    {
     "expr": "process_files_max{host=\"$host\", app=\"$application\", version=\"$version\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "persistence_counts",
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "repeat": "jvm_memory_pool_heap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_heap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_heap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pools (Non-Heap)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "repeat": "jvm_memory_pool_nonheap",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "$jvm_memory_pool_nonheap",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_memory_committed_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "commited"
      },
      {
       "expr": "jvm_memory_max_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"$jvm_memory_pool_nonheap\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Collections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_duration_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      },
      {
       "expr": "rate(jvm_gc_pause_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "{{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Pause Durations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "increase(jvm_gc_pause_duration_seconds_sum{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])/increase(jvm_gc_pause_duration_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_duration_seconds_max{host=\"$host\", app=\"$application\", version=\"$version\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      },
      {
       "expr": "increase(jvm_gc_pause_seconds_sum{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])/increase(jvm_gc_pause_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{host=\"$host\", app=\"$application\", version=\"$version\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "Allocated/Promoted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_memory_allocated_bytes_total{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "allocated"
      },
      {
       "expr": "rate(jvm_gc_memory_promoted_bytes_total{host=\"$host\", app=\"$application\", version=\"$version\"}[1m])",
       "legendFormat": "promoted"
      }
     ]
    }
   ]
  },
  {
   "title": "Classloading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes loaded",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{host=\"$host\", app=\"$application\", version=\"$version\"}",
       "legendFormat": "loaded"
      }
     ]
    },
    {
     "title": "Class load/unload rate (5m)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "delta(jvm_classes_loaded{host=\"$host\", app=\"$application\", version=\"$version\"}[5m])",
       "legendFormat": "class load rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffer Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"direct\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"direct\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{host=\"$host\", app=\"$application\", version=\"$version\", id=\"direct\"}",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"mapped\"}",
       "legendFormat": "used"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{host=\"$host\", app=\"$application\", version=\"$version\", id=\"mapped\"}",
       "legendFormat": "capacity"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{host=\"$host\", app=\"$application\", version=\"$version\", id=\"mapped\"}",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\"}[1m]))",
       "legendFormat": "HTTP"
      }
     ]
    },
    {
     "title": "Request Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{host=\"$host\", app=\"$application\", version=\"$version\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\", status!~\"5..\"}[1m]))",
       "legendFormat": "Average"
      }
     ]
    },
    {
     "title": "Request Error Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{host=\"$host\", app=\"$application\", version=\"$version\", status=~\"5..\"}[1m]))",
       "legendFormat": "HTTP - 5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "Tomcat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_current{host=\"$host\", app=\"$application\", version=\"$version\"}",
       "legendFormat": "Current Threads"
      },
      {
       "expr": "tomcat_threads_busy{host=\"$host\", app=\"$application\", version=\"$version\"}",
       "legendFormat": "Busy Threads"
      }
     ]
    },
    {
     "title": "Bytes Sent/Received",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(tomcat_global_sent_bytes_total{host=\"$host\", app=\"$application\", version=\"$version\"}[5m])",
       "legendFormat": "Bytes Sent"
      },
      {
       "expr": "rate(tomcat_global_received_bytes_total{host=\"$host\", app=\"$application\", version=\"$version\"}[5m])",
       "legendFormat": "Bytes Received"
      }
     ]
    }
   ]
  },
  {
   "title": "JDBC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_active{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_max{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Min Connections",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "jdbc_connections_max{host=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "HikiariCP Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 12 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hikaricp_connections_max{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 18, "x": 6, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "hikaricp_connections_idle{spring_boot_app=\"$application\"}",
       "legendFormat": "Idle"
      },
      {
       "expr": "hikaricp_connections_pending{spring_boot_app=\"$application\"}",
       "legendFormat": "Pending"
      },
      {
       "expr": "hikaricp_connections_active{spring_boot_app=\"$application\"}",
       "legendFormat": "Active"
      },
      {}
     ]
    },
    {
     "title": "Min Connections",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hikaricp_connections_min{host=\"$host\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "HikariCP Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sum of connection timeouts [in past 5min]",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(hikaricp_connections_timeout_total[5m])"
      }
     ]
    },
    {
     "title": "Connection Acquire Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_acquire_seconds_sum{host=\"$host\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{host=\"$host\"}[5m])",
       "legendFormat": "Acquire"
      }
     ]
    },
    {
     "title": "Connection creation time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_creation_seconds_sum{host=\"$host\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{host=\"$host\"}[5m])",
       "legendFormat": "Creation"
      }
     ]
    },
    {
     "title": "Connection usage time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "dtdurations" }
     ],
     "targets": [
      {
       "expr": "rate(hikaricp_connections_usage_seconds_sum{host=\"$host\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{host=\"$host\"}[5m])",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "RabbitMQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "rabbitmq_connections{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Channels",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "rabbitmq_channels{host=\"$host\"}"
      }
     ]
    },
    {
     "title": "Publish Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(rabbitmq_published_total{host=\"$host\"}[1m])",
       "legendFormat": "in past 1 min"
      },
      {
       "expr": "rate(rabbitmq_published_total{host=\"$host\"}[10m])",
       "legendFormat": "in past 10 min"
      }
     ]
    },
    {
     "title": "Consumption Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(rabbitmq_consumed_total{host=\"$host\"}[1m])",
       "legendFormat": "in past 1 min"
      },
      {
       "expr": "rate(rabbitmq_consumed_total{host=\"$host\"}[10m])",
       "legendFormat": "in past 10 min"
      }
     ]
    },
    {
     "title": "Rejection Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(rabbitmq_rejected_total{host=\"$host\"}[1m])",
       "legendFormat": "in past 1 min"
      },
      {
       "expr": "rate(rabbitmq_rejected_total{host=\"$host\"}[10m])",
       "legendFormat": "in past 10 mins"
      }
     ]
    },
    {
     "title": "Acknowledge Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(rabbitmq_acknowledged_total{host=\"$host\"}[1m])",
       "legendFormat": "in past 1 min"
      },
      {
       "expr": "rate(rabbitmq_acknowledged_total{host=\"$host\"}[10m])",
       "legendFormat": "in past 10 mins"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Error Events [in past 5 min]",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "increase(logback_events_total{host=\"$host\", level=\"error\"}[5m])"
      }
     ]
    },
    {
     "title": "Warn Events [in past 5 mins]",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "increase(logback_events_total{host=\"$host\", level=\"warn\"}[5m])"
      }
     ]
    },
    {
     "title": "Debug Events [in past 5 min]",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "increase(logback_events_total{host=\"$host\", level=\"debug\"}[5m])"
      }
     ]
    },
    {
     "title": "Info Events [in past 5 min]",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "increase(logback_events_total{host=\"$host\", level=\"info\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}